# FORBIDDEN_ENGLISH_WORDS.py
# Полный список запрещённых английских слов с русскими переводами
# Используется для фильтрации английских слов из русских ответов

# Словарь запрещённых слов с переводами
FORBIDDEN_WORDS_DICT = {
    # === СВЯЗКИ И ПЕРЕХОДЫ ===
    'however': 'однако',
    'moreover': 'более того',
    'furthermore': 'кроме того',
    'therefore': 'поэтому',
    'thus': 'таким образом',
    'hence': 'следовательно',
    'nevertheless': 'тем не менее',
    'nonetheless': 'тем не менее',
    'additionally': 'дополнительно',
    'consequently': 'следовательно',
    'accordingly': 'соответственно',
    'alternatively': 'альтернативно',
    'conversely': 'наоборот',
    'likewise': 'аналогично',
    'similarly': 'подобно',
    'whereas': 'тогда как',
    'whereby': 'посредством чего',
    'wherein': 'в котором',
    'thereof': 'из этого',
    'herein': 'здесь',
    'hereby': 'настоящим',
    
    # === НАРЕЧИЯ И УСИЛИТЕЛИ ===
    'essentially': 'по сути',
    'basically': 'в основном',
    'actually': 'фактически',
    'literally': 'буквально',
    'specifically': 'конкретно',
    'particularly': 'особенно',
    'especially': 'особенно',
    'generally': 'обычно',
    'typically': 'как правило',
    'normally': 'обычно',
    'commonly': 'обычно',
    'frequently': 'часто',
    'rarely': 'редко',
    'seldom': 'редко',
    'occasionally': 'иногда',
    'primarily': 'в первую очередь',
    'mainly': 'главным образом',
    'chiefly': 'в основном',
    'largely': 'в значительной степени',
    'mostly': 'в основном',
    'predominantly': 'преимущественно',
    'ultimately': 'в конечном счёте',
    'eventually': 'в конце концов',
    'finally': 'наконец',
    'lastly': 'наконец',
    'previously': 'ранее',
    'formerly': 'ранее',
    'earlier': 'раньше',
    'recently': 'недавно',
    'lately': 'в последнее время',
    'currently': 'в настоящее время',
    'presently': 'в настоящее время',
    'now': 'сейчас',
    'nowadays': 'в наше время',
    'subsequently': 'впоследствии',
    'afterwards': 'после',
    'thereafter': 'после этого',
    'initially': 'первоначально',
    'originally': 'первоначально',
    'gradually': 'постепенно',
    'progressively': 'постепенно',
    'steadily': 'неуклонно',
    'constantly': 'постоянно',
    'continually': 'постоянно',
    'continuously': 'непрерывно',
    'repeatedly': 'неоднократно',
    'frequently': 'часто',
    'immediately': 'немедленно',
    'instantly': 'мгновенно',
    'promptly': 'незамедлительно',
    'quickly': 'быстро',
    'rapidly': 'быстро',
    'swiftly': 'быстро',
    'slowly': 'медленно',
    'gradually': 'постепенно',
    'directly': 'напрямую',
    'indirectly': 'косвенно',
    'completely': 'полностью',
    'totally': 'полностью',
    'entirely': 'целиком',
    'wholly': 'полностью',
    'fully': 'полностью',
    'partially': 'частично',
    'partly': 'частично',
    'absolutely': 'абсолютно',
    'definitely': 'определённо',
    'certainly': 'определённо',
    'surely': 'конечно',
    'undoubtedly': 'несомненно',
    'clearly': 'ясно',
    'obviously': 'очевидно',
    'evidently': 'очевидно',
    'apparently': 'по-видимому',
    'seemingly': 'по-видимому',
    'presumably': 'предположительно',
    'probably': 'вероятно',
    'possibly': 'возможно',
    'perhaps': 'возможно',
    'maybe': 'может быть',
    'roughly': 'примерно',
    'approximately': 'приблизительно',
    'nearly': 'почти',
    'almost': 'почти',
    'quite': 'довольно',
    'rather': 'довольно',
    'fairly': 'довольно',
    'relatively': 'относительно',
    'comparatively': 'сравнительно',
    'extremely': 'чрезвычайно',
    'highly': 'весьма',
    'very': 'очень',
    'really': 'действительно',
    'truly': 'действительно',
    'genuinely': 'искренне',
    'indeed': 'действительно',
    'significantly': 'значительно',
    'considerably': 'значительно',
    'substantially': 'существенно',
    'notably': 'заметно',
    'remarkably': 'заметно',
    'surprisingly': 'удивительно',
    'unexpectedly': 'неожиданно',
    'fortunately': 'к счастью',
    'unfortunately': 'к сожалению',
    'sadly': 'к сожалению',
    'happily': 'к счастью',
    'luckily': 'к счастью',
    'frankly': 'откровенно',
    'honestly': 'честно',
    'personally': 'лично',
    'individually': 'индивидually',
    'collectively': 'коллективно',
    'jointly': 'совместно',
    'separately': 'отдельно',
    'independently': 'независимо',
    'simultaneously': 'одновременно',
    'concurrently': 'одновременно',
    'exclusively': 'исключительно',
    'solely': 'исключительly',
    'merely': 'всего лишь',
    'simply': 'просто',
    'just': 'просто',
    'only': 'только',
    'barely': 'едва',
    'scarcely': 'едва',
    'hardly': 'едва',
    'exactly': 'точно',
    'precisely': 'именно',
    'strictly': 'строго',
    'purely': 'чисто',
    
    # === ГЛАГОЛЫ ===
    'arrives': 'прибывает',
    'arrive': 'прибывать',
    'comes': 'приходит',
    'come': 'приходить',
    'goes': 'идёт',
    'go': 'идти',
    'becomes': 'становится',
    'become': 'становиться',
    'seems': 'кажется',
    'seem': 'казаться',
    'appears': 'появляется',
    'appear': 'появляться',
    'looks': 'выглядит',
    'look': 'выглядеть',
    'remains': 'остаётся',
    'remain': 'оставаться',
    'stays': 'остаётся',
    'stay': 'оставаться',
    'continues': 'продолжает',
    'continue': 'продолжать',
    'proceeds': 'продолжает',
    'proceed': 'продолжать',
    'begins': 'начинает',
    'begin': 'начинать',
    'starts': 'начинает',
    'start': 'начинать',
    'commences': 'начинает',
    'commence': 'начинать',
    'ends': 'заканчивает',
    'end': 'заканчивать',
    'finishes': 'завершает',
    'finish': 'завершать',
    'concludes': 'завершает',
    'conclude': 'завершать',
    'terminates': 'завершает',
    'terminate': 'завершать',
    'provides': 'предоставляет',
    'provide': 'предоставлять',
    'supplies': 'поставляет',
    'supply': 'поставлять',
    'delivers': 'доставляет',
    'deliver': 'доставлять',
    'offers': 'предлагает',
    'offer': 'предлагать',
    'presents': 'представляет',
    'present': 'представлять',
    'gives': 'даёт',
    'give': 'давать',
    'grants': 'предоставляет',
    'grant': 'предоставлять',
    'includes': 'включает',
    'include': 'включать',
    'contains': 'содержит',
    'contain': 'содержать',
    'comprises': 'включает',
    'comprise': 'включать',
    'consists': 'состоит',
    'consist': 'состоять',
    'involves': 'включает',
    'involve': 'включать',
    'encompasses': 'охватывает',
    'encompass': 'охватывать',
    'requires': 'требует',
    'require': 'требовать',
    'needs': 'нуждается',
    'need': 'нуждаться',
    'demands': 'требует',
    'demand': 'требовать',
    'necessitates': 'требует',
    'necessitate': 'требовать',
    'allows': 'позволяет',
    'allow': 'позволять',
    'permits': 'разрешает',
    'permit': 'разрешать',
    'enables': 'позволяет',
    'enable': 'позволять',
    'facilitates': 'облегчает',
    'facilitate': 'облегчать',
    'creates': 'создаёт',
    'create': 'создавать',
    'produces': 'производит',
    'produce': 'производить',
    'generates': 'генерирует',
    'generate': 'генерировать',
    'forms': 'формирует',
    'form': 'формировать',
    'makes': 'делает',
    'make': 'делать',
    'builds': 'строит',
    'build': 'строить',
    'constructs': 'строит',
    'construct': 'строить',
    'develops': 'разрабатывает',
    'develop': 'разрабатывать',
    'establishes': 'устанавливает',
    'establish': 'устанавливать',
    'takes': 'берёт',
    'take': 'брать',
    'gets': 'получает',
    'get': 'получать',
    'obtains': 'получает',
    'obtain': 'получать',
    'acquires': 'приобретает',
    'acquire': 'приобретать',
    'receives': 'получает',
    'receive': 'получать',
    'accepts': 'принимает',
    'accept': 'принимать',
    'shows': 'показывает',
    'show': 'показывать',
    'displays': 'отображает',
    'display': 'отображать',
    'demonstrates': 'демонстрирует',
    'demonstrate': 'демонстрировать',
    'reveals': 'раскрывает',
    'reveal': 'раскрывать',
    'indicates': 'указывает',
    'indicate': 'указывать',
    'suggests': 'предполагает',
    'suggest': 'предполагать',
    'implies': 'подразумевает',
    'imply': 'подразумевать',
    'tells': 'говорит',
    'tell': 'говорить',
    'says': 'говорит',
    'say': 'говорить',
    'states': 'утверждает',
    'state': 'утверждать',
    'declares': 'заявляет',
    'declare': 'заявлять',
    'announces': 'объявляет',
    'announce': 'объявлять',
    'expresses': 'выражает',
    'express': 'выражать',
    'describes': 'описывает',
    'describe': 'описывать',
    'explains': 'объясняет',
    'explain': 'объяснять',
    'clarifies': 'уточняет',
    'clarify': 'уточнять',
    'defines': 'определяет',
    'define': 'определять',
    'specifies': 'указывает',
    'specify': 'указывать',
    'means': 'означает',
    'mean': 'означать',
    'signifies': 'означает',
    'signify': 'означать',
    'represents': 'представляет',
    'represent': 'представлять',
    'symbolizes': 'символизирует',
    'symbolize': 'символизировать',
    'concerns': 'касается',
    'concern': 'касаться',
    'regards': 'касается',
    'regard': 'касаться',
    'relates': 'относится',
    'relate': 'относиться',
    'pertains': 'относится',
    'pertain': 'относиться',
    'affects': 'влияет',
    'affect': 'влиять',
    'impacts': 'влияет',
    'impact': 'влиять',
    'influences': 'влияет',
    'influence': 'влиять',
    'determines': 'определяет',
    'determine': 'определять',
    'controls': 'контролирует',
    'control': 'контролировать',
    'manages': 'управляет',
    'manage': 'управлять',
    'handles': 'обрабатывает',
    'handle': 'обрабатывать',
    'deals': 'имеет дело',
    'deal': 'иметь дело',
    'addresses': 'рассматривает',
    'address': 'рассматривать',
    'tackles': 'решает',
    'tackle': 'решать',
    'solves': 'решает',
    'solve': 'решать',
    'resolves': 'разрешает',
    'resolve': 'разрешать',
    'fixes': 'исправляет',
    'fix': 'исправлять',
    'repairs': 'ремонтирует',
    'repair': 'ремонтировать',
    'corrects': 'исправляет',
    'correct': 'исправлять',
    'improves': 'улучшает',
    'improve': 'улучшать',
    'enhances': 'улучшает',
    'enhance': 'улучшать',
    'increases': 'увеличивает',
    'increase': 'увеличивать',
    'decreases': 'уменьшает',
    'decrease': 'уменьшать',
    'reduces': 'уменьшает',
    'reduce': 'уменьшать',
    'lowers': 'снижает',
    'lower': 'снижать',
    'raises': 'повышает',
    'raise': 'повышать',
    'elevates': 'повышает',
    'elevate': 'повышать',
    'boosts': 'повышает',
    'boost': 'повышать',
    'strengthens': 'укрепляет',
    'strengthen': 'укреплять',
    'weakens': 'ослабляет',
    'weaken': 'ослаблять',
    'maintains': 'поддерживает',
    'maintain': 'поддерживать',
    'preserves': 'сохраняет',
    'preserve': 'сохранять',
    'protects': 'защищает',
    'protect': 'защищать',
    'defends': 'защищает',
    'defend': 'защищать',
    'supports': 'поддерживает',
    'support': 'поддерживать',
    'assists': 'помогает',
    'assist': 'помогать',
    'helps': 'помогает',
    'help': 'помогать',
    'aids': 'помогает',
    'aid': 'помогать',
    'contributes': 'вносит вклад',
    'contribute': 'вносить вклад',
    'participates': 'участвует',
    'participate': 'участвовать',
    'engages': 'участвует',
    'engage': 'участвовать',
    'involves': 'вовлекает',
    'involve': 'вовлекать',
    'includes': 'включает',
    'include': 'включать',
    
    # === СУЩЕСТВИТЕЛЬНЫЕ ===
    'situation': 'ситуация',
    'condition': 'условие',
    'circumstance': 'обстоятельство',
    'state': 'состояние',
    'status': 'статус',
    'position': 'позиция',
    'location': 'местоположение',
    'place': 'место',
    'spot': 'место',
    'area': 'область',
    'region': 'регион',
    'zone': 'зона',
    'sector': 'сектор',
    'direction': 'направление',
    'way': 'путь',
    'route': 'маршрут',
    'path': 'путь',
    'course': 'курс',
    'option': 'вариант',
    'choice': 'выбор',
    'alternative': 'альтернатива',
    'possibility': 'возможность',
    'opportunity': 'возможность',
    'chance': 'шанс',
    'solution': 'решение',
    'answer': 'ответ',
    'resolution': 'решение',
    'fix': 'исправление',
    'remedy': 'средство',
    'problem': 'проблема',
    'issue': 'вопрос',
    'matter': 'дело',
    'concern': 'проблема',
    'difficulty': 'трудность',
    'challenge': 'задача',
    'obstacle': 'препятствие',
    'barrier': 'барьер',
    'case': 'случай',
    'instance': 'пример',
    'example': 'пример',
    'sample': 'образец',
    'illustration': 'иллюстрация',
    'demonstration': 'демонстрация',
    'aspect': 'аспект',
    'facet': 'грань',
    'dimension': 'измерение',
    'feature': 'особенность',
    'characteristic': 'характеристика',
    'trait': 'черта',
    'quality': 'качество',
    'property': 'свойство',
    'attribute': 'атрибут',
    'element': 'элемент',
    'component': 'компонент',
    'part': 'часть',
    'piece': 'часть',
    'section': 'раздел',
    'segment': 'сегмент',
    'portion': 'часть',
    'fragment': 'фрагмент',
    'factor': 'фактор',
    'influence': 'влияние',
    'effect': 'эффект',
    'impact': 'влияние',
    'consequence': 'последствие',
    'result': 'результат',
    'outcome': 'результат',
    'process': 'процесс',
    'procedure': 'процедура',
    'method': 'метод',
    'technique': 'техника',
    'approach': 'подход',
    'strategy': 'стратегия',
    'tactic': 'тактика',
    'plan': 'план',
    'scheme': 'схема',
    'system': 'система',
    'mechanism': 'механизм',
    'structure': 'структура',
    'framework': 'основа',
    'concept': 'концепция',
    'idea': 'идея',
    'notion': 'понятие',
    'thought': 'мысль',
    'belief': 'убеждение',
    'opinion': 'мнение',
    'view': 'взгляд',
    'perspective': 'перспектива',
    'viewpoint': 'точка зрения',
    'theory': 'теория',
    'hypothesis': 'гипотеза',
    'principle': 'принцип',
    'rule': 'правило',
    'law': 'закон',
    'regulation': 'регуляция',
    'standard': 'стандарт',
    'criterion': 'критерий',
    'measure': 'мера',
    'level': 'уровень',
    'degree': 'степень',
    'extent': 'степень',
    'amount': 'количество',
    'quantity': 'количество',
    'number': 'число',
    'figure': 'цифра',
    'rate': 'ставка',
    'ratio': 'соотношение',
    'proportion': 'пропорция',
    'percentage': 'процент',
    'scope': 'масштаб',
    'scale': 'масштаб',
    'size': 'размер',
    'magnitude': 'величина',
    'range': 'диапазон',
    'span': 'промежуток',
    'duration': 'длительность',
    'period': 'период',
    'time': 'время',
    'moment': 'момент',
    'instant': 'мгновение',
    'phase': 'фаза',
    'stage': 'этап',
    'step': 'шаг',
    'point': 'точка',
    'detail': 'деталь',
    'particular': 'подробность',
    'item': 'элемент',
    'thing': 'вещь',
    'object': 'объект',
    'entity': 'сущность',
    'unit': 'единица',
    'form': 'форма',
    'type': 'тип',
    'kind': 'вид',
    'sort': 'сорт',
    'category': 'категория',
    'class': 'класс',
    'group': 'группа',
    'set': 'набор',
    'collection': 'коллекция',
    'series': 'серия',
    'sequence': 'последовательность',
    'order': 'порядок',
    'arrangement': 'расположение',
    'organization': 'организация',
    'pattern': 'паттерн',
    'design': 'дизайн',
    'model': 'модель',
    'template': 'шаблон',
    'format': 'формат',
    'style': 'стиль',
    'manner': 'манера',
    'mode': 'режим',
    'fashion': 'способ',
    
    # === ПРИЛАГАТЕЛЬНЫЕ ===
    'important': 'важный',
    'significant': 'значительный',
    'major': 'крупный',
    'key': 'ключевой',
    'main': 'главный',
    'primary': 'первичный',
    'principal': 'главный',
    'chief': 'главный',
    'essential': 'существенный',
    'fundamental': 'фундаментальный',
    'basic': 'базовый',
    'vital': 'жизненно важный',
    'critical': 'критический',
    'crucial': 'решающий',
    'necessary': 'необходимый',
    'required': 'требуемый',
    'needed': 'нужный',
    'mandatory': 'обязательный',
    'compulsory': 'обязательный',
    'optional': 'необязательный',
    'voluntary': 'добровольный',
    'possible': 'возможный',
    'potential': 'потенциальный',
    'probable': 'вероятный',
    'likely': 'вероятный',
    'unlikely': 'маловероятный',
    'impossible': 'невозможный',
    'feasible': 'осуществимый',
    'viable': 'жизнеспособный',
    'practical': 'практичный',
    'realistic': 'реалистичный',
    'theoretical': 'теоретический',
    'hypothetical': 'гипотетический',
    'actual': 'фактический',
    'real': 'реальный',
    'true': 'истинный',
    'genuine': 'подлинный',
    'authentic': 'аутентичный',
    'false': 'ложный',
    'fake': 'поддельный',
    'artificial': 'искусственный',
    'natural': 'естественный',
    'available': 'доступный',
    'accessible': 'доступный',
    'obtainable': 'доступный',
    'unavailable': 'недоступный',
    'inaccessible': 'недоступный',
    'suitable': 'подходящий',
    'appropriate': 'подходящий',
    'proper': 'правильный',
    'right': 'правильный',
    'correct': 'правильный',
    'accurate': 'точный',
    'precise': 'точный',
    'exact': 'точный',
    'wrong': 'неправильный',
    'incorrect': 'неправильный',
    'inaccurate': 'неточный',
    'imprecise': 'неточный',
    'relevant': 'релевантный',
    'pertinent': 'относящийся',
    'applicable': 'применимый',
    'related': 'связанный',
    'associated': 'ассоциированный',
    'connected': 'связанный',
    'linked': 'связанный',
    'unrelated': 'несвязанный',
    'irrelevant': 'нерелевантный',
    'similar': 'похожий',
    'alike': 'похожий',
    'comparable': 'сопоставимый',
    'equivalent': 'эквивалентный',
    'equal': 'равный',
    'identical': 'идентичный',
    'same': 'одинаковый',
    'different': 'другой',
    'distinct': 'отличный',
    'separate': 'отдельный',
    'diverse': 'разнообразный',
    'various': 'различный',
    'varied': 'разнообразный',
    'several': 'несколько',
    'multiple': 'множественный',
    'numerous': 'многочисленный',
    'many': 'многие',
    'few': 'несколько',
    'some': 'некоторые',
    'certain': 'определённый',
    'particular': 'конкретный',
    'specific': 'конкретный',
    'special': 'особый',
    'unique': 'уникальный',
    'distinctive': 'отличительный',
    'characteristic': 'характерный',
    'typical': 'типичный',
    'common': 'общий',
    'ordinary': 'обычный',
    'usual': 'обычный',
    'normal': 'нормальный',
    'standard': 'стандартный',
    'regular': 'регулярный',
    'conventional': 'обычный',
    'traditional': 'традиционный',
    'unusual': 'необычный',
    'uncommon': 'необычный',
    'rare': 'редкий',
    'exceptional': 'исключительный',
    'extraordinary': 'необыкновенный',
    'remarkable': 'замечательный',
    'notable': 'заметный',
    'noteworthy': 'заслуживающий внимания',
    'significant': 'значительный',
    'considerable': 'значительный',
    'substantial': 'существенный',
    'extensive': 'обширный',
    'comprehensive': 'всесторонний',
    'complete': 'полный',
    'total': 'полный',
    'entire': 'полный',
    'whole': 'целый',
    'full': 'полный',
    'partial': 'частичный',
    'incomplete': 'неполный',
    'limited': 'ограниченный',
    'restricted': 'ограниченный',
    'unlimited': 'неограниченный',
    'infinite': 'бесконечный',
    'finite': 'конечный',
    'broad': 'широкий',
    'wide': 'широкий',
    'narrow': 'узкий',
    'large': 'большой',
    'big': 'большой',
    'huge': 'огромный',
    'enormous': 'огромный',
    'vast': 'огромный',
    'massive': 'массивный',
    'small': 'маленький',
    'tiny': 'крошечный',
    'little': 'маленький',
    'minor': 'незначительный',
    'slight': 'небольшой',
    'minimal': 'минимальный',
    'maximum': 'максимальный',
    'high': 'высокий',
    'low': 'низкий',
    'tall': 'высокий',
    'short': 'короткий',
    'long': 'длинный',
    'brief': 'краткий',
    'extended': 'продлённый',
    'prolonged': 'продолжительный',
    'quick': 'быстрый',
    'fast': 'быстрый',
    'rapid': 'быстрый',
    'swift': 'быстрый',
    'slow': 'медленный',
    'gradual': 'постепенный',
    'sudden': 'внезапный',
    'abrupt': 'резкий',
    'immediate': 'немедленный',
    'instant': 'мгновенный',
    'prompt': 'быстрый',
    'delayed': 'задержанный',
    'late': 'поздний',
    'early': 'ранний',
    'timely': 'своевременный',
    'recent': 'недавний',
    'current': 'текущий',
    'present': 'настоящий',
    'contemporary': 'современный',
    'modern': 'современный',
    'ancient': 'древний',
    'old': 'старый',
    'new': 'новый',
    'novel': 'новый',
    'fresh': 'свежий',
    'original': 'оригинальный',
    'innovative': 'инновационный',
    'creative': 'творческий',
    'conventional': 'традиционный',
    'simple': 'простой',
    'complex': 'сложный',
    'complicated': 'сложный',
    'difficult': 'трудный',
    'hard': 'тяжёлый',
    'easy': 'лёгкий',
    'straightforward': 'прямолинейный',
    'clear': 'ясный',
    'obvious': 'очевидный',
    'evident': 'очевидный',
    'apparent': 'явный',
    'visible': 'видимый',
    'hidden': 'скрытый',
    'obscure': 'неясный',
    'vague': 'неопределённый',
    'ambiguous': 'двусмысленный',
    'unclear': 'неясный',
    'certain': 'определённый',
    'sure': 'уверенный',
    'definite': 'определённый',
    'uncertain': 'неопределённый',
    'doubtful': 'сомнительный',
    'questionable': 'сомнительный',
    'reliable': 'надёжный',
    'dependable': 'надёжный',
    'trustworthy': 'заслуживающий доверия',
    'unreliable': 'ненадёжный',
    'consistent': 'последовательный',
    'stable': 'стабильный',
    'steady': 'устойчивый',
    'constant': 'постоянный',
    'variable': 'переменный',
    'changing': 'изменяющийся',
    'fluctuating': 'колеблющийся',
    'unstable': 'нестабильный',
    'good': 'хороший',
    'excellent': 'отличный',
    'outstanding': 'выдающийся',
    'superior': 'превосходный',
    'bad': 'плохой',
    'poor': 'плохой',
    'inferior': 'низший',
    'positive': 'положительный',
    'negative': 'отрицательный',
    'favorable': 'благоприятный',
    'unfavorable': 'неблагоприятный',
    'beneficial': 'полезный',
    'harmful': 'вредный',
    'useful': 'полезный',
    'useless': 'бесполезный',
    'valuable': 'ценный',
    'worthless': 'бесценный',
    'effective': 'эффективный',
    'ineffective': 'неэффективный',
    'efficient': 'эффективный',
    'inefficient': 'неэффективный',
    'successful': 'успешный',
    'unsuccessful': 'неуспешный',
    'productive': 'продуктивный',
    'unproductive': 'непродуктивный',
    
    # === ДРУГИЕ РАСПРОСТРАНЁННЫЕ СЛОВА ===
    'also': 'также',
    'too': 'тоже',
    'as well': 'также',
    'plus': 'плюс',
    'additionally': 'дополнительно',
    'even': 'даже',
    'still': 'всё ещё',
    'yet': 'ещё',
    'already': 'уже',
    'always': 'всегда',
    'never': 'никогда',
    'sometimes': 'иногда',
    'often': 'часто',
    'usually': 'обычно',
    'much': 'много',
    'many': 'много',
    'more': 'больше',
    'most': 'больше всего',
    'less': 'меньше',
    'least': 'меньше всего',
    'some': 'некоторые',
    'any': 'любой',
    'each': 'каждый',
    'every': 'каждый',
    'all': 'все',
    'both': 'оба',
    'either': 'либо',
    'neither': 'ни один',
    'other': 'другой',
    'another': 'другой',
    'such': 'такой',
    'same': 'тот же',
    'own': 'собственный',
    'self': 'сам',
    
    # === РАЗГОВОРНЫЕ СЛОВА И СЛЕНГ ===
    'yeah': 'да',
    'yep': 'да',
    'nope': 'нет',
    'nah': 'нет',
    'yup': 'да',
    'uh-huh': 'ага',
    'uh': 'э',
    'um': 'э',
    'hmm': 'хм',
    'wow': 'вау',
    'cool': 'круто',
    'awesome': 'потрясающе',
    'amazing': 'потрясающе',
    'great': 'отлично',
    'nice': 'хорошо',
    'fine': 'хорошо',
    'okay': 'хорошо',
    'ok': 'хорошо',
    'alright': 'хорошо',
    'gotcha': 'понятно',
    'got it': 'понял',
    'I see': 'понятно',
    'sure': 'конечно',
    'right': 'верно',
    'exactly': 'точно',
    'totally': 'полностью',
    'absolutely': 'абсолютно',
    'definitely': 'определённо',
    'kinda': 'вроде',
    'sorta': 'вроде',
    'gonna': 'собираюсь',
    'wanna': 'хочу',
    'gotta': 'должен',
    'dunno': 'не знаю',
    'oops': 'ой',
    'whoops': 'ой',
    'ouch': 'ой',
    'hey': 'эй',
    'hi': 'привет',
    'hello': 'привет',
    'bye': 'пока',
    'goodbye': 'до свидания',
    'thanks': 'спасибо',
    'thank you': 'спасибо',
    'please': 'пожалуйста',
    'sorry': 'извините',
    'excuse me': 'извините',
    'pardon': 'простите',
    
    # === ЧАСТЫЕ ФРАЗЫ И ВВОДНЫЕ СЛОВА ===
    'by the way': 'кстати',
    'anyway': 'в любом случае',
    'anyhow': 'в любом случае',
    'in fact': 'на самом деле',
    'as a matter of fact': 'на самом деле',
    'to be honest': 'честно говоря',
    'honestly': 'честно',
    'frankly speaking': 'откровенно говоря',
    'speaking of': 'кстати о',
    'talking about': 'говоря о',
    'regarding': 'касательно',
    'concerning': 'относительно',
    'about': 'о',
    'kind of': 'вроде',
    'sort of': 'вроде',
    'type of': 'вид',
    'lots of': 'много',
    'plenty of': 'много',
    'a bunch of': 'куча',
    'a couple of': 'пара',
    'a few': 'несколько',
    'a little': 'немного',
    'a bit': 'немного',
    'a lot': 'много',
    'tons of': 'множество',
    'loads of': 'куча',
    'heaps of': 'куча',
    
    # === ТЕХНИЧЕСКИЕ И ПРОФЕССИОНАЛЬНЫЕ ТЕРМИНЫ ===
    'feature': 'функция',
    'functionality': 'функциональность',
    'capability': 'возможность',
    'performance': 'производительность',
    'efficiency': 'эффективность',
    'optimization': 'оптимизация',
    'implementation': 'реализация',
    'integration': 'интеграция',
    'configuration': 'конфигурация',
    'deployment': 'развёртывание',
    'infrastructure': 'инфраструктура',
    'architecture': 'архитектура',
    'framework': 'фреймворк',
    'platform': 'платформа',
    'interface': 'интерфейс',
    'workflow': 'рабочий процесс',
    'pipeline': 'конвейер',
    'dashboard': 'панель управления',
    'feedback': 'обратная связь',
    'update': 'обновление',
    'upgrade': 'обновление',
    'version': 'версия',
    'release': 'релиз',
    'patch': 'патч',
    'bug': 'баг',
    'issue': 'проблема',
    'error': 'ошибка',
    'warning': 'предупреждение',
    'alert': 'предупреждение',
    'notification': 'уведомление',
    'message': 'сообщение',
    'response': 'ответ',
    'request': 'запрос',
    'query': 'запрос',
    'search': 'поиск',
    'filter': 'фильтр',
    'sort': 'сортировка',
    'view': 'просмотр',
    'edit': 'редактирование',
    'delete': 'удаление',
    'remove': 'удалить',
    'add': 'добавить',
    'insert': 'вставить',
    'create': 'создать',
    'generate': 'сгенерировать',
    'export': 'экспорт',
    'import': 'импорт',
    'download': 'скачать',
    'upload': 'загрузить',
    'save': 'сохранить',
    'load': 'загрузить',
    'refresh': 'обновить',
    'reload': 'перезагрузить',
    'reset': 'сбросить',
    'clear': 'очистить',
    'cancel': 'отменить',
    'confirm': 'подтвердить',
    'submit': 'отправить',
    'apply': 'применить',
    'settings': 'настройки',
    'preferences': 'предпочтения',
    'options': 'опции',
    'menu': 'меню',
    'toolbar': 'панель инструментов',
    'sidebar': 'боковая панель',
    'footer': 'нижний колонтитул',
    'header': 'заголовок',
    'title': 'заголовок',
    'content': 'содержимое',
    'description': 'описание',
    'summary': 'резюме',
    'overview': 'обзор',
    'details': 'детали',
    'information': 'информация',
    'data': 'данные',
    'value': 'значение',
    'result': 'результат',
    'output': 'вывод',
    'input': 'ввод',
    'field': 'поле',
    'parameter': 'параметр',
    'argument': 'аргумент',
    'variable': 'переменная',
    'constant': 'константа',
    'function': 'функция',
    'method': 'метод',
    'class': 'класс',
    'object': 'объект',
    'instance': 'экземпляр',
    'property': 'свойство',
    'attribute': 'атрибут',
    'event': 'событие',
    'action': 'действие',
    'operation': 'операция',
    'task': 'задача',
    'job': 'работа',
    'process': 'процесс',
    'thread': 'поток',
    'service': 'сервис',
    'module': 'модуль',
    'component': 'компонент',
    'element': 'элемент',
    'item': 'элемент',
    'entry': 'запись',
    'record': 'запись',
    'file': 'файл',
    'folder': 'папка',
    'directory': 'директория',
    'path': 'путь',
    'link': 'ссылка',
    'url': 'адрес',
    'address': 'адрес',
    'location': 'местоположение',
    'position': 'позиция',
    'index': 'индекс',
    'key': 'ключ',
    'id': 'идентификатор',
    'name': 'имя',
    'label': 'метка',
    'tag': 'тег',
    'category': 'категория',
    'group': 'группа',
    'list': 'список',
    'array': 'массив',
    'set': 'набор',
    'collection': 'коллекция',
    'database': 'база данных',
    'table': 'таблица',
    'row': 'строка',
    'column': 'столбец',
    'cell': 'ячейка',
    
    # === ВРЕМЕННЫЕ И ЧАСТОТНЫЕ СЛОВА ===
    'today': 'сегодня',
    'tomorrow': 'завтра',
    'yesterday': 'вчера',
    'tonight': 'сегодня вечером',
    'morning': 'утро',
    'afternoon': 'день',
    'evening': 'вечер',
    'night': 'ночь',
    'day': 'день',
    'week': 'неделя',
    'month': 'месяц',
    'year': 'год',
    'hour': 'час',
    'minute': 'минута',
    'second': 'секунда',
    'moment': 'момент',
    'time': 'время',
    'period': 'период',
    'duration': 'продолжительность',
    'interval': 'интервал',
    'deadline': 'срок',
    'schedule': 'расписание',
    'appointment': 'встреча',
    'meeting': 'собрание',
    
    # === ВОПРОСИТЕЛЬНЫЕ СЛОВА ===
    'what': 'что',
    'when': 'когда',
    'where': 'где',
    'who': 'кто',
    'whom': 'кого',
    'whose': 'чей',
    'which': 'который',
    'why': 'почему',
    'how': 'как',
    'how much': 'сколько',
    'how many': 'сколько',
    'how long': 'как долго',
    'how often': 'как часто',
    'how far': 'как далеко',
    
    # === МОДАЛЬНЫЕ И ВСПОМОГАТЕЛЬНЫЕ ГЛАГОЛЫ ===
    'can': 'могу',
    'could': 'мог бы',
    'may': 'может',
    'might': 'мог бы',
    'must': 'должен',
    'should': 'следует',
    'would': 'бы',
    'will': 'буду',
    'shall': 'буду',
    'do': 'делать',
    'does': 'делает',
    'did': 'делал',
    'have': 'иметь',
    'has': 'имеет',
    'had': 'имел',
    'is': 'есть',
    'are': 'являются',
    'was': 'был',
    'were': 'были',
    'been': 'был',
    'being': 'будучи',
    'am': 'есть',
}

# Множество всех запрещённых слов для быстрой проверки
FORBIDDEN_WORDS_SET = set(FORBIDDEN_WORDS_DICT.keys())

# Дополнительные варианты написания с заглавной буквы
for word in list(FORBIDDEN_WORDS_DICT.keys()):
    capitalized = word.capitalize()
    if capitalized not in FORBIDDEN_WORDS_DICT:
        FORBIDDEN_WORDS_DICT[capitalized] = FORBIDDEN_WORDS_DICT[word].capitalize()

# Список для системного промпта (топ 150 самых частых + разговорные)
TOP_FORBIDDEN_FOR_PROMPT = [
    # Связки и переходы
    'however', 'moreover', 'therefore', 'thus', 'hence', 'nevertheless',
    'essentially', 'basically', 'actually', 'literally', 'specifically',
    'particularly', 'generally', 'typically', 'currently',
    # Глаголы
    'arrives', 'becomes', 'provides', 'offers', 'includes', 'contains',
    'requires', 'allows', 'enables', 'creates', 'makes', 'takes',
    'shows', 'tells', 'means', 'involves', 'affects', 'impacts',
    # Существительные
    'situation', 'condition', 'position', 'option', 'solution', 'problem',
    'issue', 'example', 'aspect', 'feature', 'element', 'factor',
    'process', 'method', 'approach', 'concept', 'idea', 'theory',
    # Прилагательные
    'important', 'significant', 'essential', 'critical', 'necessary',
    'possible', 'available', 'suitable', 'relevant', 'related', 'similar',
    'different', 'various', 'several', 'multiple', 'certain', 'specific',
    'particular', 'general', 'common', 'usual', 'normal', 'standard',
    # Наречия
    'also', 'just', 'even', 'still', 'yet', 'already', 'always', 'never',
    'sometimes', 'often', 'usually', 'really', 'very', 'much', 'many',
    'more', 'most', 'less', 'some', 'any', 'each', 'every', 'all',
    'both', 'other', 'such', 'same',
    # Разговорные слова
    'yeah', 'yep', 'nope', 'okay', 'ok', 'cool', 'awesome', 'great',
    'nice', 'fine', 'sure', 'right', 'exactly', 'totally', 'absolutely',
    'kinda', 'sorta', 'gonna', 'wanna', 'gotta', 'hey', 'thanks',
    # Вводные фразы
    'by the way', 'anyway', 'in fact', 'honestly', 'regarding', 'about',
    'kind of', 'sort of', 'a lot', 'lots of', 'plenty of',
    # Технические термины
    'feature', 'functionality', 'performance', 'implementation', 'update',
    'version', 'issue', 'error', 'message', 'request', 'response',
    'settings', 'options', 'data', 'value', 'result', 'function',
    # Вопросительные
    'what', 'when', 'where', 'who', 'which', 'why', 'how',
    # Модальные глаголы
    'can', 'could', 'may', 'might', 'must', 'should', 'would', 'will'
]